# Generated by Django 5.2 on 2025-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('Client Project', 'Client Project'), ('Internal Project', 'Internal Project')], default='Client Project', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETE', 'Complete')], default='ACTIVE', max_length=20)),
            ],
        ),
    ]
